repos:
  - repo: local
    hooks:
      - id: run-ci-tests
        name: Run CI Tests with Act
        entry: bin/run-ci-tests
        language: system
        stages: [pre-commit]
        pass_filenames: false